version: '3'  
services:
  tolbarweb/biblioteca-frontend-ceiba:
    image: tolbarweb/biblioteca-frontend-ceiba
    container_name: tolbarweb/biblioteca-frontend-ceiba
    build: 
      context: ./
    ports:  
    - "8290:80"
networks:
  network_biblioteca:
     external: true