version: '3'  
services:
  biblioteca-frontend-ceiba:
    image: biblioteca-frontend-ceiba
    container_name: biblioteca-frontend-ceiba
    build: 
      context: ./
    ports:  
    - "8290:80"
networks:
  network_biblioteca:
     external: true